# Train audio config template
# model:
#   name: mobilenetv2
#   input_size: 224
# training:
#   batch_size: 32
#   epochs: 20
#   learning_rate: 0.001
# dataset:
#   train_dir: data/dataset/audio/train
#   val_dir: data/dataset/audio/val
#   test_dir: data/dataset/audio/test
